# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: $(Date:yyMMdd-HHmm)$(Rev:.r).$(SourceBranchName)

# No CI trigger; run on a schedule only.
trigger: none

# Do not trigger on PRs.
pr: none

parameters:
- name: releaseBuild
  displayName: Release Build
  type: boolean
  default: false

- name: buildArtifacts
  displayName: Build Artifacts
  type: object
  default:
  - x64-win-release-cp37
  - x64-win-debug-cp37
  - x64-win-release-cp38
  - x64-win-release-cp39
  - x64-linux-release-cp37
  - x64-linux-debug-cp37
  - x64-linux-release-cp38
  - x64-linux-release-cp39

- name: testArtifacts
  displayName: Test Artifacts
  type: object
  default: [x64-win-release-cp37, x64-linux-release-cp37]

- name: testGroups
  displayName: Test Groups
  type: object
  default: [ops, plugin]

- name: testTensorflowPackage
  displayName: TensorFlow Package Version
  type: string
  default: tensorflow-cpu==2.7.0

- name: enableTests
  displayName: Enable Tests
  type: boolean
  default: true

- name: emailTo
  displayName: Email Results To
  type: string
  default: $(emailTo) # the default is stored in the pipeline as a variable

# For building manylinux2010-compliant Linux wheels:
# resources:
#   containers:
#   - container: manylinux
#     image: tensorflow/tensorflow:2.3.0-custom-op-ubuntu16

stages:
- stage: buildStage
  displayName: Build
  jobs:
  - ${{each artifact in parameters.buildArtifacts}}:
    - template: build.yml
      parameters:
        artifact: ${{artifact}}
        releaseBuild: ${{parameters.releaseBuild}}

- ${{if parameters.enableTests}}:
  - stage: testStage
    displayName: Test
    dependsOn: buildStage
    jobs:
    - template: test.yml
      parameters:
        testGroups: ${{parameters.testGroups}}
        artifacts: ${{parameters.testArtifacts}}
        tensorflowPackage: ${{parameters.testTensorflowPackage}}

- stage: reportStage
  displayName: Report Results
  ${{if parameters.enableTests}}:
    dependsOn: [buildStage, testStage]
  ${{if not(parameters.enableTests)}}:
    dependsOn: [buildStage]
  condition: succeededOrFailed()
  pool: DirectML_TF2_Windows_Pool
  jobs:
  - template: report.yml
    parameters:
      emailTo: ${{parameters.emailTo}}
