# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: $(Date:yyMMdd-HHmm)$(Rev:.r).$(SourceBranchName)

# No CI trigger; run on a schedule only.
trigger: none

pr:
- main
- releases/*
- user/pavignol/test123

- name: buildArtifacts
  displayName: Build Artifacts
  type: object
  default:
  - x64-win-release-cp37
  - x64-linux-release-cp37

# TODO: Make our own docker image for our unique dependencies (e.g. clang) instead of using the tensorflow core one
# For building manylinux2010-compliant Linux wheels:
resources:
  containers:
  - container: manylinux
    image: tensorflow/tensorflow:2.5.0-custom-op-ubuntu16

stages:
- stage: buildStage
  displayName: Build
  jobs:
  - ${{each artifact in parameters.buildArtifacts}}:
    - template: build.yml
      parameters:
        artifact: ${{artifact}}
