# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

parameters:
- name: emailTo
  type: string
  default: ''
- name: buildMetadataArtifactName
  type: string
  default: build
- name: testResultsArtifactName
  type: string
  default: test
- name: enableTests
  type: boolean
  default: true
- name: pluginBuildPipeline
  type: string
  default: current

jobs:
- job: report
  timeoutInMinutes: 30
  displayName: Report Results
  condition: succeededOrFailed()
  workspace:
    clean: all
  steps:
  - checkout: self
    fetchDepth: 1

  - download: ${{parameters.pluginBuildPipeline}}
    artifact: ${{parameters.buildMetadataArtifactName}}
    displayName: Download Build Metadata

  - ${{if parameters.enableTests}}:
    - task: DownloadBuildArtifacts@0
      displayName: Download Test Summaries
      continueOnError: true
      inputs:
        buildType: current
        downloadType: single
        artifactName: ${{parameters.testResultsArtifactName}}
        itemPattern: |
          ${{parameters.testResultsArtifactName}}/matrix.json
          ${{parameters.testResultsArtifactName}}/test_summary.json
          ${{parameters.testResultsArtifactName}}/test_summary.xml
          ${{parameters.testResultsArtifactName}}/agent_summary.json

  - task: PowerShell@2
    name: createHtml
    displayName: Create Report HTML
    condition: succeededOrFailed()
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)
    inputs:
      targetType: filePath
      filePath: pipelines/CreateReportEmail.ps1
      arguments: >
        -TestArtifactsPath $(System.ArtifactsDirectory)/${{parameters.testResultsArtifactName}}
        -BuildArtifactsPath $(System.ArtifactsDirectory)/${{parameters.buildMetadataArtifactName}}
        -PipelineRunID $(Build.BuildID)
        -AccessToken $(System.AccessToken)
        -OutputHtmlPath $(System.ArtifactsDirectory)/results.html
        -EmailTo ${{parameters.emailTo}}
  - task: PkgESSendMail@10
    displayName: Send Email
    inputs:
      to: $(createHtml.emailTo)
      subject: $(createHtml.emailSubject)
      bodyFile: $(System.ArtifactsDirectory)/results.html
      isHtml: true
  - task: PublishBuildArtifacts@1
    displayName: Upload Report
    inputs:
      pathToPublish: $(System.ArtifactsDirectory)/results.html
      artifactName: ${{parameters.testResultsArtifactName}}