name: Python Code Check
on: [ pull_request]
jobs:
  python-code-check:
    name: Check Python Code Formatting And Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: pip install -r requirements.txt
    - run: "black build.py --check --diff --verbose"
    - run: "black generate_op_defs_core.py --check --diff --verbose"
    - run: "black test/plugin --check --diff --verbose"
    - run: "black tfdml --check --diff --verbose"
    - run: pylint build.py
    - run: pylint generate_op_defs_core.py
    - run: pylint test/plugin
    - run: pylint tfdml
