name: Python Code Check
on:
  pull_request:
    types: [opened, synchronize, edited, reopened]
    branches: [main, release/*]
concurrency:
  group: python-check-${{ github.ref }}
  cancel-in-progress: true
jobs:
  python-code-check:
    name: Check Python Code Formatting And Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - run: pip install -r requirements.txt
    - run: "black . --check --diff --verbose"
    - run: pylint *.py
    - run: pylint test
    - run: pylint tfdml
