name: Python Code Check
on: [push, pull_request]
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
    - run: pip install pylint
    - run: pylint $(git ls-files '*.py')
